// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrcL5fFFF76_9CS2kU8LVY3pqnzQy-KaM',
    appId: '1:97967926541:web:d3df3fbba89832a938d444',
    messagingSenderId: '97967926541',
    projectId: 'dukabase-ce7ed',
    authDomain: 'dukabase-ce7ed.firebaseapp.com',
    storageBucket: 'dukabase-ce7ed.firebasestorage.app',
    measurementId: 'G-2G03ETNT2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhpDYtr9Wxk-K1fnILXYljShDrMt6Vx68',
    appId: '1:97967926541:android:102bbce0f374f72438d444',
    messagingSenderId: '97967926541',
    projectId: 'dukabase-ce7ed',
    storageBucket: 'dukabase-ce7ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsHNLy9HVSxJBlG0Uj0m4QR3A3YkZlSqA',
    appId: '1:97967926541:ios:4d7d40816f4c533b38d444',
    messagingSenderId: '97967926541',
    projectId: 'dukabase-ce7ed',
    storageBucket: 'dukabase-ce7ed.firebasestorage.app',
    iosBundleId: 'com.example.dukabase',
  );
}
